name: dos_flutter_ideas001
description: A Flutter ledger app using Firestore and Typesense search with Material 3 and dark mode.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.9.0
  firebase_core: ^3.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
